/**
 * Every bespoke route: what it is for, and what it accepts.
 *
 * The handlers already validate — every one of them calls `parseBody(req,
 * someSchema)`. What was missing is a way to ask that question from OUTSIDE a
 * request, which is what generating a contract document requires. The summary
 * sits here rather than being derived from the path because "post /pos/session/
 * close" is not a description of anything; an endpoint list is only navigable if
 * a human wrote the line.
 *
 * The map is duplicated information, and duplicated information rots. It is
 * safe here only because `tests/openapi.test.ts` reads the route modules and
 * fails if any route validates a body this map does not record, records one it
 * does not validate, or names a different schema than the handler uses. That
 * test is the reason this file is allowed to exist.
 *
 * Generic entity CRUD is absent on purpose: those bodies come from entity
 * metadata, so `generate.ts` derives them and nothing needs listing here.
 *
 * Keys are `METHOD /path` in Express form (`:id`); the generator rewrites the
 * parameters into OpenAPI form (`{id}`).
 */
import type { ZodType } from "zod";
import {
  aggregateSchema,
  assignmentRuleSchema,
  automationRollbackSchema,
  automationRunSchema,
  automationStatusSchema,
  awardQuoteSchema,
  billPaymentSchema,
  cartCheckoutSchema,
  cashMovementSchema,
  clientErrorsSchema,
  changePasswordSchema,
  closeSessionSchema,
  countEntriesSchema,
  createAutomationSchema,
  createCartSchema,
  createGoodsReceiptSchema,
  createInvoiceSchema,
  createJournalEntrySchema,
  createLandedCostSchema,
  createPurchaseOrderSchema,
  createPurchaseRequestSchema,
  createPurchaseReturnSchema,
  createSupplierQuoteSchema,
  orderRequestSchema,
  createQuoteSchema,
  createDeliverySchema,
  createSalesOrderSchema,
  createSalesReturnSchema,
  createUserSchema,
  customFieldSchema,
  createVendorBillSchema,
  eInvoiceSchema,
  erpSyncSchema,
  emailIdsSchema,
  emailRestoreSchema,
  importSchema,
  integrationTestSchema,
  integrationToggleSchema,
  mobileConfigSchema,
  passwordConfirmSchema,
  paymentSchema,
  posCheckoutSchema,
  posSessionSchema,
  profileSchema,
  registerDeviceSchema,
  rejectSchema,
  releaseSchema,
  reserveSchema,
  replaceDocumentSchema,
  reportExportSchema,
  revalueSchema,
  sendEmailSchema,
  settingsBagSchema,
  totpCodeSchema,
  transitionSchema,
  unregisterDeviceSchema,
  updateAutomationSchema,
  updateUserSchema,
  userSettingsSchema,
  webhookSchema,
} from "@/lib/http/body";

export interface RouteDoc {
  /** One line, written by a person. It is the whole endpoint list in a viewer. */
  summary: string;
  /** The request body, for routes that take one. Absent means the route has none. */
  schema?: ZodType;
}

export const ROUTE_DOCS: Record<string, RouteDoc> = {
  "PATCH /admin/users/:id": { summary: "Update a user, their position, password or 2FA state", schema: updateUserSchema },
  "PATCH /auth/password": { summary: "Change your own password (verifies the current one)", schema: changePasswordSchema },
  "PATCH /auth/profile": { summary: "Update your own profile", schema: profileSchema },
  "PATCH /auth/settings": { summary: "Update your own preferences (theme, density, sync interval)", schema: userSettingsSchema },
  "PATCH /automation/integrations/:provider": { summary: "Enable, disable or reconfigure an integration provider", schema: integrationToggleSchema },
  "PATCH /automation/settings": { summary: "Update automation governance settings", schema: settingsBagSchema },
  "PATCH /automations/:id": { summary: "Update an automation rule", schema: updateAutomationSchema },
  "PATCH /mobile/configs/:id": { summary: "Update a mobile screen-visibility rule", schema: mobileConfigSchema },
  "PATCH /system/settings": { summary: "Update system settings", schema: settingsBagSchema },
  "POST /accounting/revalue": { summary: "Revalue open foreign-currency balances at a period end", schema: revalueSchema },
  "POST /admin/users": { summary: "Create a user", schema: createUserSchema },
  "POST /aggregate": { summary: "Group and aggregate any entity (the basis of every report)", schema: aggregateSchema },
  "POST /auth/2fa/disable": { summary: "Turn off two-factor authentication", schema: passwordConfirmSchema },
  "POST /auth/2fa/enable": { summary: "Confirm two-factor enrolment with a code from the authenticator", schema: totpCodeSchema },
  "POST /auth/2fa/recovery-codes": { summary: "Reissue two-factor recovery codes", schema: passwordConfirmSchema },
  "POST /automation/assignment": { summary: "Create or replace an assignment rule", schema: assignmentRuleSchema },
  "POST /automation/integrations/:provider/test": { summary: "Check that a provider is reachable and configured", schema: integrationTestSchema },
  "POST /automations": { summary: "Create an automation rule", schema: createAutomationSchema },
  "POST /automations/:id/rollback": { summary: "Roll an automation rule back to an earlier version", schema: automationRollbackSchema },
  "POST /automations/:id/run": { summary: "Run an automation rule now (live, or as a dry run)", schema: automationRunSchema },
  "POST /automations/:id/status": { summary: "Activate, pause or draft an automation rule", schema: automationStatusSchema },
  "POST /carts": { summary: "Open a sales cart", schema: createCartSchema },
  "POST /carts/:id/checkout": { summary: "Close a cart — tender it at the register, or invoice it to the customer's account", schema: cartCheckoutSchema },
  "POST /email/move": { summary: "Move many messages to another folder", schema: emailIdsSchema },
  "POST /email/purge": { summary: "Permanently delete many messages", schema: emailIdsSchema },
  "POST /email/restore": { summary: "Restore many messages from Trash", schema: emailRestoreSchema },
  "POST /email/send": { summary: "Send a message over SMTP", schema: sendEmailSchema },
  "POST /email/trash": { summary: "Move many messages to Trash", schema: emailIdsSchema },
  "POST /entities/:entity/:id/transitions": { summary: "Apply a lifecycle action to any record", schema: transitionSchema },
  "POST /erp/sync": { summary: "Push one record to SAP now, through the same path the automatic triggers use", schema: erpSyncSchema },
  "POST /goods-receipts": { summary: "Receive goods against a purchase order line", schema: createGoodsReceiptSchema },
  "POST /import/:entity": { summary: "Import records from a CSV or Excel file", schema: importSchema },
  "POST /import/:entity/job": { summary: "Start a background import and return its job id", schema: importSchema },
  "POST /invoices": { summary: "Create an invoice with its lines", schema: createInvoiceSchema },
  "POST /invoices/:id/e-invoice": { summary: "Build the e-Fatura / e-Arşiv document for an invoice", schema: eInvoiceSchema },
  "POST /invoices/:id/payments": { summary: "Record a payment against an invoice", schema: paymentSchema },
  "POST /journal-entries": { summary: "Post a manual journal entry", schema: createJournalEntrySchema },
  "POST /mobile/configs": { summary: "Create a mobile screen-visibility rule", schema: mobileConfigSchema },
  "POST /pos/checkout": { summary: "Ring up a sale — invoices it, posts the ledger and issues the stock", schema: posCheckoutSchema },
  "GET /pos/session/:id/report": { summary: "The till report — X mid-shift, Z at close; same arithmetic either way" },
  "POST /pos/session/:id/cash": { summary: "Record cash into or out of the drawer that is not a sale", schema: cashMovementSchema },
  "POST /pos/session/close": { summary: "Close the till and record the counted cash", schema: closeSessionSchema },
  "POST /pos/session/open": { summary: "Open a till session with its float", schema: posSessionSchema },
  "POST /purchase-orders": { summary: "Create a purchase order with its lines", schema: createPurchaseOrderSchema },
  "POST /purchase-orders/:id/reject": { summary: "Reject a purchase order awaiting approval", schema: rejectSchema },
  "POST /quotes": { summary: "Create a quote with its lines", schema: createQuoteSchema },
  "POST /reports/export": { summary: "Render a report to a styled Excel workbook", schema: reportExportSchema },
  "POST /sales-returns": { summary: "Create a sales return with its lines", schema: createSalesReturnSchema },
  "POST /stock-counts/:id/entries": { summary: "Record what was actually found during a physical count", schema: countEntriesSchema },
  "POST /vendor-bills": { summary: "Create a vendor bill with its lines", schema: createVendorBillSchema },
  "POST /vendor-bills/:id/payments": { summary: "Pay a vendor bill", schema: billPaymentSchema },
  "POST /webhooks": { summary: "Register an outbound webhook", schema: webhookSchema },
  "POST /devices": { summary: "Register this device for push notifications; call on every launch, tokens rotate", schema: registerDeviceSchema },
  "POST /devices/unregister": { summary: "Stop pushing to this device", schema: unregisterDeviceSchema },
  "POST /client-errors": { summary: "Report crashes and handled failures from a client, in a batch", schema: clientErrorsSchema },
  "PUT /carts/:id": { summary: "Replace a cart's lines", schema: replaceDocumentSchema },
  "PUT /invoices/:id": { summary: "Replace an invoice's lines and recompute its totals", schema: replaceDocumentSchema },
  "PUT /purchase-orders/:id": { summary: "Replace a purchase order's lines", schema: replaceDocumentSchema },
  "PUT /quotes/:id": { summary: "Replace a quote's lines", schema: replaceDocumentSchema },
  "PUT /vendor-bills/:id": { summary: "Replace a vendor bill's lines", schema: replaceDocumentSchema },

  // ---- routes with no request body ------------------------------------
  "POST /auth/login": { summary: "Sign in with email and password; sets the session cookie" },
  "POST /auth/logout": { summary: "Sign out of this device" },
  "POST /auth/logout-all": { summary: "Sign out everywhere — bumps the token epoch so every issued token stops working" },
  "POST /auth/refresh": {
    summary:
      "Exchange the current session for a fresh one — rotates the token (the old one is revoked) and rebuilds grants from the caller's current position",
  },
  "GET /auth/me": { summary: "Who is signed in: user, position, screens and resolved permissions" },
  "GET /auth/security/activity": { summary: "Your recent sign-ins and security changes" },
  "POST /auth/2fa/setup": { summary: "Begin two-factor enrolment — returns the secret and otpauth URI" },
  "GET /screens": { summary: "The screen catalogue used by the nav and the position editor" },
  "GET /screens/grantable": { summary: "The screens you are allowed to grant to a position" },
  "GET /permissions/catalog": { summary: "Every grantable operation, plus each base role's defaults" },
  "GET /admin/users": { summary: "List users visible to you" },
  "GET /mobile/config": { summary: "Your resolved mobile screen configuration" },
  "GET /mobile/screens": { summary: "Screens the mobile app can show, flagged for mobile support" },
  "GET /mobile/configs": { summary: "The raw mobile visibility rules" },
  "DELETE /mobile/configs/:id": { summary: "Delete a mobile visibility rule" },
  "GET /system/settings": { summary: "System settings" },
  "GET /admin/custom-fields": { summary: "Fields added to the model at runtime, and which entities may be extended" },
  "POST /admin/custom-fields": { summary: "Add a field to an entity without a deploy; publishes the model and reconciles the schema", schema: customFieldSchema },
  "DELETE /admin/custom-fields/:id": { summary: "Retire a custom field — it stops appearing; the column and its data stay" },
  "POST /admin/metadata/republish": { summary: "Republish the metadata version — makes a definition change live" },
  "GET /admin/releases": { summary: "The metadata release log" },
  "GET /meta": { summary: "The metadata version and every entity definition" },
  "GET /meta/:entity": { summary: "One entity's definition" },
  "GET /stats": { summary: "Headline counts for the dashboards" },
  "GET /activity": { summary: "The audit trail, most recent first" },
  "GET /search": { summary: "Search across every entity you may read" },
  "POST /search/reindex": { summary: "Rebuild the search index from the records themselves" },
  "GET /export/:entity": { summary: "Export an entity to CSV or Excel" },
  "GET /import/:entity/template": { summary: "An empty import template with one header row" },
  "GET /import/:entity/job/:id": { summary: "Poll a background import's progress and result" },
  "GET /quotes/:id": { summary: "A quote with its lines" },
  "POST /quotes/:id/convert": { summary: "Convert a quote into an invoice" },
  "POST /deals/:id/quote": { summary: "Convert an opportunity into a draft quote, seeded from its amount" },
  "POST /quotes/:id/order": { summary: "Convert an accepted quote into a draft sales order" },
  "POST /sales-orders": { summary: "Raise a sales order with its lines", schema: createSalesOrderSchema },
  "GET /sales-orders/:id": { summary: "A sales order with its lines" },
  "PUT /sales-orders/:id": { summary: "Replace a sales order's header and lines", schema: replaceDocumentSchema },
  "POST /sales-orders/:id/confirm": { summary: "Confirm a sales order — holds the stock it promises" },
  "GET /sales-orders/:id/fulfilment": { summary: "Ordered, shipped and outstanding quantities per order line" },
  "POST /sales-orders/:id/deliveries": {
    summary: "Raise a delivery note (irsaliye) for a load going out against this order",
    schema: createDeliverySchema,
  },
  "GET /delivery-notes/:id": { summary: "A delivery note with its lines" },
  "POST /delivery-notes/:id/post": { summary: "Dispatch a delivery note — issues the stock at cost and posts COGS" },
  "POST /delivery-notes/:id/invoice": { summary: "Invoice a dispatched load; the stock already left, so this bills only" },
  "GET /invoices/:id": { summary: "An invoice with its lines" },
  "GET /invoices/:id/payments": { summary: "Payments recorded against an invoice" },
  "GET /e-invoices/:id/xml": { summary: "The UBL document exactly as stored" },
  "POST /e-invoices/:id/send": { summary: "Transmit an e-Fatura document to the integrator" },
  "GET /sales-returns": { summary: "List sales returns" },
  "GET /sales-returns/:id": { summary: "A sales return with its lines" },
  "POST /sales-returns/:id/post": { summary: "Post a sales return — restocks the goods at cost and reverses the sale" },
  "GET /purchase-orders/:id": { summary: "A purchase order with its lines" },
  "POST /purchase-orders/:id/submit": { summary: "Submit a purchase order for approval" },
  "POST /purchase-orders/:id/approve": { summary: "Approve a purchase order awaiting your decision" },
  "GET /goods-receipts/:id": { summary: "A goods receipt with its lines" },
  "POST /goods-receipts/:id/post": { summary: "Post a goods receipt — takes the stock in at the receipt cost" },
  "POST /purchase-requests": { summary: "Raise a purchase request — what is wanted, why and by when", schema: createPurchaseRequestSchema },
  "GET /purchase-requests/:id": { summary: "A purchase request with its lines" },
  "GET /purchase-requests/:id/comparison": { summary: "Every supplier offer against a request, line by line, cheapest marked" },
  "POST /purchase-requests/:id/order": { summary: "Order a request directly from a known supplier, skipping the quote round", schema: orderRequestSchema },
  "POST /supplier-quotes": { summary: "Record a supplier offer against a purchase request", schema: createSupplierQuoteSchema },
  "POST /supplier-quotes/:id/award": { summary: "Award a quote and raise its draft purchase order; the losing quotes are kept", schema: awardQuoteSchema },
  "POST /purchase-returns": { summary: "Send goods back to a supplier", schema: createPurchaseReturnSchema },
  "GET /purchase-returns/:id": { summary: "A purchase return with its lines" },
  "POST /purchase-returns/:id/post": { summary: "Post a return — goods out at cost, the payable reduced" },
  "POST /landed-costs": {
    summary: "Record freight, duty or insurance against a goods receipt",
    schema: createLandedCostSchema,
  },
  "GET /landed-costs/:id/preview": { summary: "What each receipt line would carry, without applying it" },
  "POST /landed-costs/:id/apply": { summary: "Add the charge to the goods — the moving average rises" },
  "GET /products/:id/suppliers": { summary: "Who can supply this product: agreed price, MOQ, lead time and what was last paid" },
  "GET /vendor-bills/:id": { summary: "A vendor bill with its lines" },
  "POST /vendor-bills/:id/receive": { summary: "Three-way match a vendor bill against its receipt, booking any price variance" },
  "GET /accounting/trial-balance": { summary: "The trial balance" },
  "GET /accounting/vat-summary": { summary: "VAT position for a period — the basis of the KDV beyannamesi" },
  "POST /journal-entries/:id/post": { summary: "Post a journal entry to the ledger" },
  "POST /journal-entries/:id/void": { summary: "Void a posted journal entry with a reversing entry" },
  "POST /recurring/run": { summary: "Run the recurring billing cycle now" },
  "POST /cron/tick": { summary: "Run every due scheduled job now" },
  "GET /jobs": { summary: "The scheduled-job registry and each job's last run" },
  "GET /inventory/on-hand": { summary: "Stock on hand per product and location" },
  "GET /inventory/low-stock": { summary: "Products at or below their reorder level" },
  "GET /inventory/lots": { summary: "On-hand batches of a product in a warehouse, in picking order (FEFO)" },
  "GET /inventory/lots/:id/trace": { summary: "Where a batch came from and who received it — the recall question" },
  "POST /inventory/lots/expire": { summary: "Mark batches whose date has passed; the stock stays valued but becomes unpickable" },
  "GET /inventory/replenishment": {
    summary: "What to reorder, how much, and from whom — measured against available rather than on-hand stock",
  },
  "GET /inventory/availability": { summary: "On hand, reserved and available for one product in one warehouse" },
  "POST /inventory/alerts/scan": { summary: "Run the stock-condition scan now rather than waiting for the nightly job" },
  "POST /inventory/reserve": { summary: "Hold stock for a document; the availability check runs under a row lock", schema: reserveSchema },
  "POST /inventory/release": { summary: "Give back a document's hold — or drop it when the goods shipped", schema: releaseSchema },
  "POST /operations/alerts/scan": { summary: "Run the purchasing, count and till condition scan now" },
  "POST /inventory/reconcile": { summary: "Check every stock balance against the movement ledger; `?apply=true` repairs drift" },
  "POST /stock-transfers/:id/post": { summary: "Post a stock transfer — moves the goods and their value between locations" },
  "POST /stock-adjustments/:id/post": { summary: "Post a stock adjustment" },
  "POST /stock-counts/:id/sheet": { summary: "Generate the count sheet, freezing the system quantity and cost" },
  "POST /stock-counts/:id/post": { summary: "Post a physical count — applies the variance, not the absolute quantity" },
  "GET /pricing/resolve": { summary: "The price for a product, given the customer and quantity" },
  "GET /pos/lookup": { summary: "Find a product by barcode or SKU" },
  "GET /pos/session": { summary: "The current till session" },
  "GET /carts": { summary: "List sales carts" },
  "GET /carts/:id": { summary: "A cart with its lines" },
  "DELETE /carts/:id": { summary: "Delete a draft cart" },
  "POST /carts/:id/send": { summary: "Hand the basket to the cash desk and assign its pickup code" },
  "POST /carts/:id/suspend": { summary: "Park a queued cart" },
  "POST /carts/:id/resume": { summary: "Put a parked cart back in the queue" },
  "POST /carts/:id/cancel": { summary: "Reject a cart at the register, or void a draft" },
  "GET /automation/catalog": { summary: "The builder catalogue: entities, fields, operators and action types" },
  "GET /automation/stats": { summary: "Automation dashboard figures" },
  "GET /automations": { summary: "List automation rules" },
  "GET /automations/:id": { summary: "One automation rule" },
  "DELETE /automations/:id": { summary: "Delete an automation rule" },
  "GET /automation/runs": { summary: "Automation execution logs" },
  "GET /automation/runs/:id": { summary: "One automation run, with its captured input" },
  "POST /automation/runs/:id/retry": { summary: "Re-run a past execution, replaying its input" },
  "GET /automation/live": { summary: "Which rules are running right now" },
  "POST /automation/run-now": { summary: "Queue and drain every active schedule-triggered automation" },
  "GET /automation/queue": { summary: "The processing queue: pending, retrying and dead-lettered items" },
  "POST /automation/queue/process": { summary: "Drain the automation queue to completion" },
  "POST /automation/queue/:id/retry": { summary: "Retry one queued automation item" },
  "DELETE /automation/queue/:id": { summary: "Drop one item from the automation queue" },
  "GET /automation/assignment": { summary: "List assignment rules" },
  "DELETE /automation/assignment/:id": { summary: "Delete an assignment rule" },
  "GET /automation/settings": { summary: "Automation governance settings" },
  "GET /automation/integrations": { summary: "Integration providers and their configuration state" },
  "GET /webhooks": { summary: "Registered outbound webhooks" },
  "DELETE /webhooks/:id": { summary: "Delete a webhook" },
  "POST /webhooks/:id/test": { summary: "Send a test delivery to a webhook" },
  "POST /webhooks/echo": { summary: "Local webhook receiver — unauthenticated, echoes the signature it was sent" },
  "POST /devices/test": { summary: "Send a test push to your own devices — exercises the whole path and records the outcome" },
  "GET /devices": { summary: "The devices you can be reached on, and why one might be silent" },
  "GET /notifications": { summary: "Your notification inbox" },
  "POST /notifications": { summary: "Mark notifications as read" },
  "POST /notifications/delete": { summary: "Delete notifications" },
  "POST /files/upload": { summary: "Upload a file (multipart) and store it against a record" },
  "GET /files/:id/download": { summary: "Download a stored file" },
  "POST /email/sync": { summary: "Pull new messages from the IMAP server" },
  "GET /email/list": { summary: "Paged mailbox listing — full records minus the message body" },
  "DELETE /email/folders/:id": { summary: "Delete a custom mail folder, returning its messages to their base folder" },
  // ---- SAP PI/PO -------------------------------------------------------
  "POST /erp/inbound": { summary: "Receive a message from SAP PI/PO (XML or JSON). Basic auth; idempotent on MessageId." },
  "GET /erp/messages": { summary: "Everything exchanged with SAP, newest first" },
  "POST /erp/dispatch": { summary: "Send every queued message to SAP now rather than waiting for the job" },
  "POST /erp/messages/:id/retry": { summary: "Re-queue a dead-lettered message after fixing its cause" },
  "GET /health": { summary: "Liveness and readiness, including a database ping. Public." },
  "GET /metrics": { summary: "Request, error, deadlock and in-flight counters, plus which instance holds the scheduler lease" },
  "GET /openapi.json": { summary: "This document" },
  "POST /realtime/ticket": { summary: "Mint a single-use, seconds-long ticket for opening the realtime socket" },
};
