/**
 * Phase 2 — Metadata bootstrap.
 *
 * Registers the CRM entities, validates them, and publishes version 1 so the
 * resolver has an active version at import time. Editing metadata at runtime
 * goes through `metadataRegistry.createDraft` + governed `publish` (Phase 14).
 */
import { systemClock } from "@/lib/core/clock";
import { MetadataRegistry } from "./registry";
import { MetadataResolver } from "./resolver";
import type { EntityDef } from "./types";
// Entity definitions come from the shared contracts package, so the backend
// and the web app cannot describe the same entity differently. Which of them
// each app REGISTERS still differs, and legitimately: the browser has no use
// for outbox rows or webhook deliveries.
import {
  accountEntity,
  assignmentRuleEntity,
  auditEntryEntity,
  automationIntegrationEntity,
  automationQueueEntity,
  automationRuleEntity,
  automationRunEntity,
  automationSettingEntity,
  billPaymentEntity,
  branchEntity,
  calendarEventEntity,
  cartEntity,
  cartLineEntity,
  chequeEntity,
  companyEntity,
  currencyEntity,
  exchangeRateEntity,
  dealEntity,
  dealerEntity,
  departmentEntity,
  eInvoiceEntity,
  emailEntity,
  emailFolderEntity,
  employeeEntity,
  fileEntity,
  fiscalPeriodEntity,
  goodsReceiptEntity,
  goodsReceiptLineEntity,
  invoiceEntity,
  invoiceLineEntity,
  journalEntryEntity,
  journalLineEntity,
  labelTemplateEntity,
  ledgerAccountEntity,
  mobileScreenConfigEntity,
  noteEntity,
  notificationEntity,
  notificationStateEntity,
  outboxEventEntity,
  paymentEntity,
  posSessionEntity,
  positionEntity,
  priceListEntity,
  priceListItemEntity,
  productEntity,
  productCategoryEntity,
  productBarcodeEntity,
  productVariantValueEntity,
  supplierProductEntity,
  landedCostEntity,
  purchaseReturnEntity,
  purchaseReturnLineEntity,
  purchaseRequestEntity,
  purchaseRequestLineEntity,
  supplierQuoteEntity,
  supplierQuoteLineEntity,
  stockLotEntity,
  posMovementEntity,
  customFieldEntity,
  purchaseOrderEntity,
  purchaseOrderLineEntity,
  quoteEntity,
  quoteLineEntity,
  recurringPlanEntity,
  revokedTokenEntity,
  schedulerLeaseEntity,
  uomEntity,
  stockReservationEntity,
  deviceTokenEntity,
  clientErrorEntity,
  productUomEntity,
  erpMappingEntity,
  erpMessageEntity,
  operationsAlertEntity,
  searchDocumentEntity,
  salesOrderEntity,
  salesOrderLineEntity,
  deliveryNoteEntity,
  deliveryNoteLineEntity,
  salesReturnEntity,
  salesReturnLineEntity,
  securityEventEntity,
  stockAdjustmentEntity,
  stockAlertEntity,
  stockBalanceEntity,
  stockCountEntity,
  stockCountLineEntity,
  stockMovementEntity,
  stockTransferEntity,
  supplierEntity,
  systemSettingEntity,
  taskEntity,
  taxRateEntity,
  todoEntity,
  userEntity,
  userSettingEntity,
  vendorBillEntity,
  vendorBillLineEntity,
  warehouseEntity,
  webhookDeliveryEntity,
  webhookEndpointEntity,
} from "./entities";

export const crmEntities: EntityDef[] = [
  accountEntity,
  dealEntity,
  taskEntity,
  // sales
  revokedTokenEntity,
  schedulerLeaseEntity,
  uomEntity,
  stockReservationEntity,
  deviceTokenEntity,
  clientErrorEntity,
  productUomEntity,
  erpMappingEntity,
  erpMessageEntity,
  operationsAlertEntity,
  searchDocumentEntity,
  salesOrderEntity,
  salesOrderLineEntity,
  deliveryNoteEntity,
  deliveryNoteLineEntity,
  cartEntity,
  cartLineEntity,
  salesReturnEntity,
  salesReturnLineEntity,
  quoteEntity,
  quoteLineEntity,
  invoiceEntity,
  invoiceLineEntity,
  // branches & dealers
  branchEntity,
  companyEntity,
  dealerEntity,
  // people
  departmentEntity,
  employeeEntity,
  // inventory / purchasing
  warehouseEntity,
  supplierEntity,
  stockCountEntity,
  stockCountLineEntity,
  stockMovementEntity,
  stockBalanceEntity,
  stockAlertEntity,
  chequeEntity,
  eInvoiceEntity,
  auditEntryEntity,
  outboxEventEntity,
  webhookEndpointEntity,
  webhookDeliveryEntity,
  notificationEntity,
  notificationStateEntity,
  purchaseOrderEntity,
  purchaseOrderLineEntity,
  goodsReceiptEntity,
  goodsReceiptLineEntity,
  stockTransferEntity,
  stockAdjustmentEntity,
  // barcode labels + POS
  labelTemplateEntity,
  posSessionEntity,
  // accounting
  ledgerAccountEntity,
  fiscalPeriodEntity,
  journalEntryEntity,
  journalLineEntity,
  vendorBillEntity,
  vendorBillLineEntity,
  billPaymentEntity,
  // finance / catalog
  priceListEntity,
  priceListItemEntity,
  productEntity,
  productCategoryEntity,
  productBarcodeEntity,
  productVariantValueEntity,
  supplierProductEntity,
  landedCostEntity,
  purchaseReturnEntity,
  purchaseReturnLineEntity,
  purchaseRequestEntity,
  purchaseRequestLineEntity,
  supplierQuoteEntity,
  supplierQuoteLineEntity,
  stockLotEntity,
  posMovementEntity,
  customFieldEntity,
  currencyEntity,
  exchangeRateEntity,
  taxRateEntity,
  paymentEntity,
  recurringPlanEntity,
  // productivity + comms (bespoke screens; system → hidden from auto-nav)
  noteEntity,
  todoEntity,
  fileEntity,
  emailEntity,
  emailFolderEntity,
  calendarEventEntity,
  // auth / access control
  positionEntity,
  userEntity,
  userSettingEntity,
  mobileScreenConfigEntity,
  securityEventEntity,
  // automation platform (system entities; admin-gated, off the auto-nav)
  automationRuleEntity,
  automationRunEntity,
  automationQueueEntity,
  assignmentRuleEntity,
  automationSettingEntity,
  automationIntegrationEntity,
  systemSettingEntity,
];

export const metadataRegistry = new MetadataRegistry();

const draft = metadataRegistry.createDraft(crmEntities);
metadataRegistry.publish(draft.version, "system", systemClock.isoNow());

export const metadata = new MetadataResolver(metadataRegistry);

export { MetadataRegistry } from "./registry";
export { MetadataResolver } from "./resolver";
export {
  buildCreateSchema,
  buildUpdateSchema,
  validateRecord,
} from "./validation";
export type { ValidationOutcome, FieldIssue } from "./validation";
export * from "./types";
